FROM ubuntu 

RUN apt update && apt install libc-dev gcc curl -y

RUN curl https://raw.githubusercontent.com/cd-c89/sysinc/refs/heads/main/macros/tester.c -o tester.c

RUN curl https://raw.githubusercontent.com/cd-c89/sysinc/refs/heads/main/macros/tester.sh -o tester.sh

COPY macros.c .
